using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class BoardGameWinDetector : MonoBehaviour
{
    // Start is called before the first frame update

    public string goalBoxToDetect;

    BoardGameManager gameManager;
    Dictionary<string, bool> boxes;

    void Start(){
        gameManager = GameObject.Find("BoardGameManager").GetComponent<BoardGameManager>();
    }

    private void OnTriggerStay(Collider other){
        if(other.name != "GrabVolumeBig"){ //Avoid the collision generated by the hands
            if(other.name == goalBoxToDetect){
                gameManager.changeBoxStatus(goalBoxToDetect, true);
            }
        }
    }
     private void OnTriggerExit(Collider other){
         if(other.name != "GrabVolumeBig"){ 
            gameManager.changeBoxStatus(goalBoxToDetect, false);
        }
    }

}
